### ISSUE TITLE
Package.json lists two  `cf-deployment-tracker-client` dependencies

### ISSUE THREAD

**Issue by ptitzler** [IBM-Bluemix/get-started-node#1]
```
 "cf-deployment-tracker-client": "^0.1.1",
 "cf-deployment-tracker-client": "*"
```

If an older version is picked up some of the metadata (like runtime environment) is not set properly. Please ruse `"cf-deployment-tracker-client": "^0.x"`. Thanks!

**Comment by rossfenrick** [comment]
fixed. thank you
