### ISSUE TITLE
Line 5 should be corrected in the source.

### ISSUE THREAD

**Issue by andrewferrier** [IBM-Bluemix/get-started-node#2]
The README.md for this example states:

```
In the root directory, update line 5 of server.js to look up the environment variable

var port = process.env.VCAP_APP_PORT || 8080;
```

However, this should probably be fixed in the source code for the sample itself. At the moment, this is an extra hurdle to get it working out of the box. Because the `||` is in place, this will still work locally with Node.JS anyway.

**Comment by rossfenrick** [comment]
The reason we don't have this in the source itself is we want users to learn how to implement environment variables, instead of us just doing it for them.
